# Generated by Django 2.2 on 2022-06-25 10:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
    ]
